repo: 'accessibility-fixer-upper'
canvasCourse: 'web-dev-3'

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - accessibility
  - aria-landmarks
  - google-fonts
  - html-good-semantics
  - forms
  - nav-focus
  - main-link-focus

html:
  - path: 'index.html'
    has:
      - ['link[href*="Merriweather"]', 'The Google Font, `Merriweather` (regular, italic & bold) is missing']
      - 'nav#nav'
      - ['.nav a[href="#about"]', 'The “About” link should jump down the page to an element with the ID of `#about`']
      - ['.nav a[href="#shrubs"]', 'The “Shrubs” link should jump down the page to an element with the ID of `#shrubs`']
      - ['.nav a[href="#prices"]', 'The “Prices” link should jump down the page to an element with the ID of `#prices`']
      - ['.nav a[href="#news"]', 'The “News” link should jump down the page to an element with the ID of `#news`']
      - ['.nav a[href="#contact"]', 'The “About” link should jump down the page to an element with the ID of `#contact`']
      - 'main#main'
      - 'section#shrubs'
      - ['#shrubs img[src*="shrub-1"][aria-details][alt=""]', 'The “Grassy shrubs” `<img>` tag needs more description than an `alt=""` can provide, `aria-details=""` should point to an ID with all the necessary information']
      - ['#shrubs img[src*="shrub-2"][aria-details][alt=""]', 'The “Shrubs with laurels” `<img>` tag needs more description than an `alt=""` can provide, `aria-details=""` should point to an ID with all the necessary information']
      - ['#shrubs img[src*="shrub-3"][aria-details][alt=""]', 'The “Two-level shrubbery” `<img>` tag needs more description than an `alt=""` can provide, `aria-details=""` should point to an ID with all the necessary information']
      - ['#shrubs > div > ul > li:first-child > div[id]', 'All the `<div>` tags within the “Products” list, that come after the `<img>` tags, should have IDs that `aria-details` can point to']
      - ['#shrubs > div > ul > li:nth-child(2) > div[id]', 'All the `<div>` tags within the “Products” list, that come after the `<img>` tags, should have IDs that `aria-details` can point to']
      - ['#shrubs > div > ul > li:last-child > div[id]', 'All the `<div>` tags within the “Products” list, that come after the `<img>` tags, should have IDs that `aria-details` can point to']
      - 'section#prices'
      - 'table > thead th:nth-child(2)[scope="col"]'
      - 'table > thead th:nth-child(3)[scope="col"]'
      - 'table > thead th:nth-child(4)[scope="col"]'
      - 'table > tbody tr:nth-child(1) > th[scope="row"]'
      - 'table > tbody tr:nth-child(2) > th[scope="row"]'
      - 'table > tbody tr:nth-child(3) > th[scope="row"]'
      - 'section#news'
      - ['#news ol li:nth-child(1) p a[aria-label]', 'The “Read more” links need unique `aria-label` attributes because the text is all the same but they link to different locations']
      - ['#news ol li:nth-child(2) p a[aria-label]', 'The “Read more” links need unique `aria-label` attributes because the text is all the same but they link to different locations']
      - ['#news ol li:nth-child(3) p a[aria-label]', 'The “Read more” links need unique `aria-label` attributes because the text is all the same but they link to different locations']
      - 'form div:nth-child(1) label[for]'
      - 'form div:nth-child(1) input[id]'
      - 'form div:nth-child(2) label[for]'
      - 'form div:nth-child(2) input[id]'
      - 'form div:nth-child(2) input[type]'
      - 'form div:nth-child(3) label[for]'
      - 'form div:nth-child(3) select[id]'
    searchNot:
      - '\<title\>Things and stuff and junk\<\/title\>'

css:
  - path: 'css/main.css'
    valid: true
    bestPractices: true
    hasNot:
      - ['a', ['text-decoration'], 'Links not part of navigation should always be underlined']
    search:
      - ['.nav a:focus', 'There should be `:focus` states for the navigation links']
  - path: 'css/modules.css'
    locked: true
  - path: 'css/grid.css'
    locked: true
  - path: 'css/type.css'
    locked: true

screenshots:
  - path: 'index.html'
    sizes: [320, 960]
